name: Build Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/cache@v2
      with:
        path: ./target/*
        key: ${{ github.sha }}
  dockerize:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v2
      with:
        path: ./target/*
        key: ${{ github.sha }}
    - name: Build the Docker image
      run: docker build . --file src/main/docker/Dockerfile --tag demo:$(date +%s)
