name: Docker Image CI

on:
  workflow_run:
    workflows: [ "Java CI with Maven" ]
    branches: [ "main" ]
    types: 
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file src/main/docker/Dockerfile --tag demo:$(date +%s)
